"""add pricing_json to tenants

Revision ID: 3310ae409395
Revises: 3d480092ad1b
Create Date: 2026-03-06 14:54:27.117417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3310ae409395'
down_revision: Union[str, Sequence[str], None] = '3d480092ad1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('pricing_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'pricing_json')
    # ### end Alembic commands ###
