"""init upload_records

Revision ID: 8a40197da8d5
Revises: 
Create Date: 2025-10-30 10:55:16.602436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a40197da8d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('s3_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'rejected', name='uploadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_records_lead_id'), 'upload_records', ['lead_id'], unique=False)
    op.create_index(op.f('ix_upload_records_object_key'), 'upload_records', ['object_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_records_object_key'), table_name='upload_records')
    op.drop_index(op.f('ix_upload_records_lead_id'), table_name='upload_records')
    op.drop_table('upload_records')
    # ### end Alembic commands ###
